# -*- coding: utf-8 -*-
"""TesteTarget.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqntehNE_l-idGpBmIjzKC__2bKkc-Lk

# Exercicio 1)

Resposta: Ao final do processamento, a variavel SOMA terá o valor 91. Isso ocorre porque o laço while soma o valor de K em cada iteração, incrementado-o de 1 até atingir o valor 13. A soma de 1 a 13 é 91.

# Exercicio 2)
"""

def fibonacci_sequence(n):
    a, b = 0, 1
    while a <= n:
        if a == n:
            return True
        a, b = b, a + b
    return False

# Entrada
numero = int(input("Informe um número: "))

# Verifica se o número está na sequência de Fibonacci
if fibonacci_sequence(numero):
    print(f"O número {numero} pertence à sequência de Fibonacci.")
else:
    print(f"O número {numero} não pertence à sequência de Fibonacci.")

"""# Exercicio 3)"""

import json

# Carrega os dados do JSON (exemplo simplificado)
faturamento_mensal = [
    1000, 2000, 3000, 0, 1500, 0, 500, 4000, 2500, 0, 0, 600, 0, 3500
]

# Remove dias sem faturamento
faturamento_valido = [valor for valor in faturamento_mensal if valor > 0]

# Calcula o menor e maior faturamento
menor_faturamento = min(faturamento_valido)
maior_faturamento = max(faturamento_valido)

# Calcula a média mensal
media_mensal = sum(faturamento_valido) / len(faturamento_valido)

# Conta o número de dias acima da média
dias_acima_da_media = sum(1 for valor in faturamento_valido if valor > media_mensal)

# Exibe os resultados
print(f"Menor faturamento: R${menor_faturamento}")
print(f"Maior faturamento: R${maior_faturamento}")
print(f"Dias acima da média: {dias_acima_da_media}")

"""# Exercicio 4)"""

# Faturamento por estado
faturamento = {
    'SP': 67836.43,
    'RJ': 36678.66,
    'MG': 29229.88,
    'ES': 27165.48,
    'Outros': 19849.53
}

# Valor total de faturamento
faturamento_total = sum(faturamento.values())

# Calcula o percentual de cada estado
for estado, valor in faturamento.items():
    percentual = (valor / faturamento_total) * 100
    print(f"{estado}: {percentual:.2f}%")

"""# Exercicio 5)"""

def inverter_string(texto):
    string_invertida = ""
    for i in range(len(texto) - 1, -1, -1):
        string_invertida += texto[i]
    return string_invertida

# Entrada de exemplo
texto = input("Informe uma string: ")

# Inverte a string
resultado = inverter_string(texto)

# Exibe a string invertida
print(f"String invertida: {resultado}")